// Code generated by protoc-gen-go.
// source: proofTx.proto
// DO NOT EDIT!

/*
Package proofTx is a generated protocol buffer package.

It is generated from these files:
	proofTx.proto

It has these top-level messages:
	ProofTX
	SupercededBy
*/
package proofTx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ProofTX_ProofType int32

const (
	ProofTX_NULL          ProofTX_ProofType = 0
	ProofTX_SECP256K1     ProofTX_ProofType = 1
	ProofTX_SECP256K1SHA2 ProofTX_ProofType = 2
)

var ProofTX_ProofType_name = map[int32]string{
	0: "NULL",
	1: "SECP256K1",
	2: "SECP256K1SHA2",
}
var ProofTX_ProofType_value = map[string]int32{
	"NULL":          0,
	"SECP256K1":     1,
	"SECP256K1SHA2": 2,
}

func (x ProofTX_ProofType) String() string {
	return proto.EnumName(ProofTX_ProofType_name, int32(x))
}

type SupercededBy_ProofType int32

const (
	SupercededBy_NULL          SupercededBy_ProofType = 0
	SupercededBy_SECP256K1     SupercededBy_ProofType = 1
	SupercededBy_SECP256K1SHA2 SupercededBy_ProofType = 2
)

var SupercededBy_ProofType_name = map[int32]string{
	0: "NULL",
	1: "SECP256K1",
	2: "SECP256K1SHA2",
}
var SupercededBy_ProofType_value = map[string]int32{
	"NULL":          0,
	"SECP256K1":     1,
	"SECP256K1SHA2": 2,
}

func (x SupercededBy_ProofType) String() string {
	return proto.EnumName(SupercededBy_ProofType_name, int32(x))
}

type ProofTX struct {
	Type       ProofTX_ProofType `protobuf:"varint,1,opt,name=type,enum=ProofTX_ProofType" json:"type,omitempty"`
	Name       string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Threshold  int32             `protobuf:"varint,3,opt,name=threshold" json:"threshold,omitempty"`
	Data       string            `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
	PubKeys    [][]byte          `protobuf:"bytes,5,rep,name=PubKeys,proto3" json:"PubKeys,omitempty"`
	Signatures [][]byte          `protobuf:"bytes,6,rep,name=Signatures,proto3" json:"Signatures,omitempty"`
	Digests    [][]byte          `protobuf:"bytes,7,rep,name=Digests,proto3" json:"Digests,omitempty"`
	PreImages  [][]byte          `protobuf:"bytes,8,rep,name=PreImages,proto3" json:"PreImages,omitempty"`
	Supercede  *SupercededBy     `protobuf:"bytes,9,opt,name=supercede" json:"supercede,omitempty"`
}

func (m *ProofTX) Reset()         { *m = ProofTX{} }
func (m *ProofTX) String() string { return proto.CompactTextString(m) }
func (*ProofTX) ProtoMessage()    {}

func (m *ProofTX) GetSupercede() *SupercededBy {
	if m != nil {
		return m.Supercede
	}
	return nil
}

type SupercededBy struct {
	Type      SupercededBy_ProofType `protobuf:"varint,1,opt,name=type,enum=SupercededBy_ProofType" json:"type,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PubKeys   [][]byte               `protobuf:"bytes,3,rep,name=PubKeys,proto3" json:"PubKeys,omitempty"`
	Digests   [][]byte               `protobuf:"bytes,4,rep,name=Digests,proto3" json:"Digests,omitempty"`
	Threshold int32                  `protobuf:"varint,5,opt,name=threshold" json:"threshold,omitempty"`
}

func (m *SupercededBy) Reset()         { *m = SupercededBy{} }
func (m *SupercededBy) String() string { return proto.CompactTextString(m) }
func (*SupercededBy) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("ProofTX_ProofType", ProofTX_ProofType_name, ProofTX_ProofType_value)
	proto.RegisterEnum("SupercededBy_ProofType", SupercededBy_ProofType_name, SupercededBy_ProofType_value)
}
